# ============================================================
# EnsDeploy.cmake —— 部署辅助函数
# ============================================================
# 当前仅实现 Windows 下 Qt 运行时的自动部署（windeployqt）。
# 后续若需打包 / 安装脚本，可在此扩展。
#
# 设计要点：
#   - include_guard(GLOBAL) 保证本模块只被完整解释一次。
#   - 部署相关变量用 CACHE INTERNAL 保存，确保在任意目录（根目录或
#     add_subdirectory 的子目录）里调用 ens_windeployqt() 都能读到。
#   - 初始化（找 Qt 根目录、找 windeployqt、生成辅助脚本）是「懒」的：
#     第一次调用 ens_windeployqt() 时才执行，此时 Qt5 已经 find_package 过，
#     因此即使 include(EnsDeploy) 写在了 find_package(Qt5) 之前也没关系。
#   - ens_windeployqt(<target>) 必须在创建 target 的同一 CMakeLists 目录里调用，
#     直接给该目标挂 POST_BUILD，链接完成后自动运行 windeployqt。
#   - 多个目标可能并发 POST_BUILD 到同一目录（如 bin/Debug），helper 脚本里的
#     file(LOCK ... GUARD GLOBAL) 负责跨进程串行化，避免 "Cannot create" 冲突。
#   - ens_finalize_deploy() 保留为无操作，兼容根 CMakeLists.txt 的现有调用。
# ============================================================

include_guard(GLOBAL)

set(_EnsDeploy_lock   "${CMAKE_BINARY_DIR}/ens_deploy.lock")
set(_EnsDeploy_helper "${CMAKE_BINARY_DIR}/ens_deploy_helper.cmake")

# 懒初始化：查找 windeployqt、推导 Qt 根目录、生成 cmake -P 辅助脚本。
# 用 CACHE INTERNAL 保存，跨目录调用可见；已初始化则直接返回。
function(ens_deploy_init)
    if(_EnsDeploy_windeployqt AND _EnsDeploy_qt_root)
        return()
    endif()

    set(_qt_root "")
    if(DEFINED Qt5Core_DIR)
        get_filename_component(_qt_root "${Qt5Core_DIR}/../../../" ABSOLUTE)
    elseif(DEFINED ENV{QT5_DIR})
        set(_qt_root "$ENV{QT5_DIR}")
    elseif(DEFINED ENV{QT_DIR})
        set(_qt_root "$ENV{QT_DIR}")
    endif()

    find_program(_wd NAMES windeployqt HINTS "${_qt_root}/bin")
    set(_EnsDeploy_qt_root "${_qt_root}" CACHE INTERNAL "EnsDeploy Qt root")
    set(_EnsDeploy_windeployqt "${_wd}" CACHE INTERNAL "EnsDeploy windeployqt")

    if(_wd)
        # 生成一个 cmake -P 脚本：拿到文件锁后再调用 windeployqt。
        # 脚本在顶层作用域（cmake -P）运行，锁用 GUARD PROCESS：进程退出时自动释放，
        # 正好串行化多个并发的 cmake -P 部署进程。
        file(WRITE "${_EnsDeploy_helper}" [[
# Auto-generated by EnsDeploy.cmake — do not edit.
set(_qt_root "${QT_ROOT}")
set(_windeployqt "${WINDEPLOYQT}")
set(_exe "${TARGET_FILE}")
set(_dir "${TARGET_DIR}")
set(_mode "${DEPLOY_MODE}")

if(NOT _windeployqt OR NOT EXISTS "${_windeployqt}")
    message(FATAL_ERROR "windeployqt not found: ${_windeployqt}")
endif()
if(NOT _mode)
    set(_mode --release)
endif()

# 强制 windeployqt 使用我们链接的 MSVC Qt，而不是 PATH 里可能排在前面的 MinGW Qt。
set(ENV{QTDIR} "${_qt_root}")
set(ENV{PATH} "${_qt_root}/bin;$ENV{PATH}")

file(LOCK "${ENS_DEPLOY_LOCK}" GUARD PROCESS TIMEOUT 300)
execute_process(
    COMMAND "${_windeployqt}"
        ${_mode}
        --no-translations
        --no-compiler-runtime
        --no-opengl-sw
        --no-angle
        --dir "${_dir}"
        "${_exe}"
    RESULT_VARIABLE _rc
)
if(NOT _rc EQUAL 0)
    message(FATAL_ERROR "windeployqt failed for ${_exe} (exit ${_rc})")
endif()
]]
        )
    else()
        message(WARNING "windeployqt not found; Qt runtime DLLs will not be deployed automatically.")
    endif()
endfunction()

# ------------------------------------------------------------------
# 登记一个需要部署 Qt 运行时的可执行目标
# 注意：必须在创建 target 的同一目录里调用。
# ------------------------------------------------------------------
function(ens_windeployqt target)
    if(NOT WIN32)
        return()
    endif()
    if(NOT TARGET ${target})
        message(WARNING "ens_windeployqt: target '${target}' does not exist in this directory.")
        return()
    endif()

    ens_deploy_init()
    if(NOT _EnsDeploy_windeployqt)
        return()
    endif()

    add_custom_command(TARGET ${target} POST_BUILD
        COMMAND "${CMAKE_COMMAND}"
            -D "QT_ROOT=${_EnsDeploy_qt_root}"
            -D "WINDEPLOYQT=${_EnsDeploy_windeployqt}"
            -D "TARGET_FILE=$<TARGET_FILE:${target}>"
            -D "TARGET_DIR=$<TARGET_FILE_DIR:${target}>"
            -D "DEPLOY_MODE=$<IF:$<CONFIG:Debug>,--debug,--release>"
            -D "ENS_DEPLOY_LOCK=${_EnsDeploy_lock}"
            -P "${_EnsDeploy_helper}"
        COMMENT "Deploying Qt runtime for ${target}"
        VERBATIM
    )
endfunction()

# ------------------------------------------------------------------
# 兼容性占位：早期版本在根 CMakeLists.txt 末尾调用 ens_finalize_deploy()，
# 现在部署在 ens_windeployqt() 里完成，这里什么都不做。
# ------------------------------------------------------------------
function(ens_finalize_deploy)
    # no-op
endfunction()
