# EnsDeploy.cmake —— Windows 下 Qt 运行时自动部署（windeployqt）。
#   - include_guard(GLOBAL)：本模块只解释一次，函数全局可见（子目录无需重复 include）。
#   - 懒初始化：首次调用 ens_windeployqt() 时才定位 Qt/windeployqt（此时 Qt5 已 find_package）。
#   - 部署变量用 CACHE INTERNAL 保存，跨目录可见。
#   - helper 脚本用 file(LOCK ... GUARD PROCESS) 串行化并发部署，避免 "Cannot create" 冲突。

include_guard(GLOBAL)

set(_EnsDeploy_lock   "${CMAKE_BINARY_DIR}/ens_deploy.lock")
set(_EnsDeploy_helper "${CMAKE_BINARY_DIR}/ens_deploy_helper.cmake")

# 懒初始化：定位 windeployqt、推导 Qt 根目录、生成 cmake -P 辅助脚本。
function(ens_deploy_init)
    if(_EnsDeploy_windeployqt AND _EnsDeploy_qt_root)
        return()
    endif()

    set(_qt_root "")
    if(DEFINED Qt5Core_DIR)
        get_filename_component(_qt_root "${Qt5Core_DIR}/../../../" ABSOLUTE)
    elseif(DEFINED ENV{QT5_DIR})
        set(_qt_root "$ENV{QT5_DIR}")
    elseif(DEFINED ENV{QT_DIR})
        set(_qt_root "$ENV{QT_DIR}")
    endif()

    find_program(_wd NAMES windeployqt HINTS "${_qt_root}/bin")
    set(_EnsDeploy_qt_root "${_qt_root}" CACHE INTERNAL "EnsDeploy Qt root")
    set(_EnsDeploy_windeployqt "${_wd}" CACHE INTERNAL "EnsDeploy windeployqt")

    if(_wd)
        # cmake -P 脚本：取到文件锁后再调 windeployqt。锁用 GUARD PROCESS，
        # 进程退出即释放，串行化多个并发的 cmake -P 部署进程。
        file(WRITE "${_EnsDeploy_helper}" [[
# Auto-generated by EnsDeploy.cmake — do not edit.
set(_qt_root "${QT_ROOT}")
set(_windeployqt "${WINDEPLOYQT}")
set(_exe "${TARGET_FILE}")
set(_dir "${TARGET_DIR}")
set(_mode "${DEPLOY_MODE}")

if(NOT _windeployqt OR NOT EXISTS "${_windeployqt}")
    message(FATAL_ERROR "windeployqt not found: ${_windeployqt}")
endif()
if(NOT _mode)
    set(_mode --release)
endif()

# 强制 windeployqt 使用我们链接的 MSVC Qt，而非 PATH 中可能靠前的 MinGW Qt。
set(ENV{QTDIR} "${_qt_root}")
set(ENV{PATH} "${_qt_root}/bin;$ENV{PATH}")

file(LOCK "${ENS_DEPLOY_LOCK}" GUARD PROCESS TIMEOUT 300)
execute_process(
    COMMAND "${_windeployqt}"
        ${_mode}
        --no-translations
        --no-compiler-runtime
        --no-opengl-sw
        --no-angle
        --dir "${_dir}"
        "${_exe}"
    RESULT_VARIABLE _rc
)
if(NOT _rc EQUAL 0)
    message(FATAL_ERROR "windeployqt failed for ${_exe} (exit ${_rc})")
endif()
]]
        )
    else()
        message(WARNING "windeployqt not found; Qt runtime DLLs will not be deployed automatically.")
    endif()
endfunction()

# 登记需部署 Qt 运行时的可执行目标（须在创建 target 的同一目录调用）。
function(ens_windeployqt target)
    if(NOT WIN32)
        return()
    endif()
    if(NOT TARGET ${target})
        message(WARNING "ens_windeployqt: target '${target}' does not exist in this directory.")
        return()
    endif()

    ens_deploy_init()
    if(NOT _EnsDeploy_windeployqt)
        return()
    endif()

    add_custom_command(TARGET ${target} POST_BUILD
        COMMAND "${CMAKE_COMMAND}"
            -D "QT_ROOT=${_EnsDeploy_qt_root}"
            -D "WINDEPLOYQT=${_EnsDeploy_windeployqt}"
            -D "TARGET_FILE=$<TARGET_FILE:${target}>"
            -D "TARGET_DIR=$<TARGET_FILE_DIR:${target}>"
            -D "DEPLOY_MODE=$<IF:$<CONFIG:Debug>,--debug,--release>"
            -D "ENS_DEPLOY_LOCK=${_EnsDeploy_lock}"
            -P "${_EnsDeploy_helper}"
        COMMENT "Deploying Qt runtime for ${target}"
        VERBATIM
    )
endfunction()
